config/routes.rb
Rails.application.routes.draw do
  root "links#index"
  resources :links do
    member do
      put "up", to: "links#upvote"
      put "down", to: "links#downvote"
    end
    resources :comments do
      member do
        put "up", to: "comments#upvote"
        put "down", to: "comments#downvote"
      end
    end
  end
  resources :comments do
    member do
      put "up", to: "comments#upvote"
      put "down", to: "comments#downvote"
    end
    resources :comments do
      member do
        put "up", to: "comments#upvote"
        put "down", to: "comments#downvote"
      end
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  acts_as_votable
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  before_save :linkify
  has_many :comments, as: :commentable
  acts_as_votable

  def linkify
    if !(self.url.include?("http"))
      self.url = "http://"+self.url
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
  has_many :comments
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :find_commentable
  before_action :authenticate_user!, except: [:index, :show]
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = current_user.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    #@comment = current_user.comments.build(comment_params)
    @comment = @commentable.comments.build(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_back(fallback_location: @commentable) }
        format.json { render :show, status: :created, location: @comment }
        
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote 
    @comment = Comment.find(params[:id])
    @comment.upvote_by current_user
    redirect_back(fallback_location: @commentable)
  end  
  
  def downvote
    @comment = Comment.find(params[:id])
    @comment.downvote_by current_user
    redirect_back(fallback_location: @commentable)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, users_attributes: [:id])
    end

    def find_commentable
      @commentable = Comment.find(params[:comment_id]) if params[:comment_id]
      @commentable = Link.find(params[:link_id]) if params[:link_id]
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /links
  # GET /links.json

  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote 
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_back(fallback_location: @commentable)
  end  
  
  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_back(fallback_location: @commentable)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:url, :title, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_comment.html.erb
<li>
    <%= link_to "+", up_comment_path(comment), method: :put %>
    <%= comment.weighted_score %>
    <%= link_to "-", down_comment_path(comment), method: :put %>
  <%= comment.body %> -
  <small>Submitted <%= time_ago_in_words(comment.created_at) %> ago </small>

    <%= form_for [comment, Comment.new] do |f| %>
        <%= f.text_area :body, placeholder: "Add a Reply" %><br/>
        <%= f.submit "Reply"  %>
    <% end %>

  <ul>
      <%= render partial: 'comments/comment', collection: comment.comments %>
  </ul>

</li>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditMockup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# user is logged in, show log out link %>
    <% if current_user.present? %>
      <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
    <%# user is not logged in, show signup and login links %>
    <% else %>
      <%= link_to 'Sign In', new_user_session_path %> |
      <%= link_to 'Register Now!', new_user_registration_path %>
    <% end %>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :link_url %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :link_title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, id: :link_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Reddit Mockup</h1>
<p>After registeration and logging in, you can make a new post, comment on other posts, vote on posts, comment on comments, comments on comments of comments, vote on comments, vote on comments of comments of comments of comments and ... </p>

<table>
  <thead>
    <tr>
      <th>Votes</th>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link_to "+", up_link_path(link), method: :put %>
          <%= link.weighted_score %>
          <%= link_to "-", down_link_path(link), method: :put %>
        </td>
        <td><%= link_to link.title, link %></td>
        <td><%= link.user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<strong><%= link_to(@link.title, @link.url, target: "_blank") %></strong><br/>
<small>Submitted <%= time_ago_in_words(@link.created_at) %> ago by <%= @link.user.email %> </small>
<p id="notice"><%= notice %></p>

<ul>
  <%= render(partial: 'comments/comment', collection: @link.comments) %>
</ul>

<p>
  <%= @link.text %>
</p>

<% if @link.user == current_user %>
  <%= link_to 'Edit', edit_link_path(@link) %> |
  <%= link_to 'Delete', @link, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
  <%= link_to 'Back', links_path %>

<h3>Comments</h3>
<%= form_for [@link, Comment.new] do |f| %>
<%= f.text_area :body, placeholder: "Add a comment" %><br/>
<%= f.submit "Add Comment" %>
<% end %>